// @ts-check
module.exports = {
  docs: {
    General: [{ type: 'autogenerated', dirName: 'General' }],
    // @ts-expect-error
    'Mutation Testing': require('./docs/mutation-testing-elements/sidebar'),
    // @ts-expect-error
    StrykerJS: require('./docs/stryker-js/sidebar'),
    'Stryker.NET': [{ type: 'autogenerated', dirName: 'stryker-net' }],
    Stryker4s: [{ type: 'autogenerated', dirName: 'stryker4s' }],
  },
};
