import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import strykerJSSidebar from './docs/stryker-js/sidebar.json';

const sidebars: SidebarsConfig = {
  docs: {
    General: [{ type: 'autogenerated', dirName: 'General' }],
    'Mutation Testing': [{ type: 'autogenerated', dirName: 'mutation-testing-elements' }],
    StrykerJS: strykerJSSidebar,
    'Stryker.NET': [{ type: 'autogenerated', dirName: 'stryker-net' }],
    Stryker4s: [{ type: 'autogenerated', dirName: 'stryker4s' }],
  },
};

export default sidebars;
