name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          # Use same version of node for netlify and CI build
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Docusaurus cache
        if: ${{ github.ref != 'refs/heads/develop' }}
        uses: actions/cache@v5
        with:
          path: |
            .docusaurus
            node_modules/.cache
          key: ${{ runner.os }}-docusaurus-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}-${{ hashFiles('**/*.md', '**/*.mdx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-docusaurus-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-docusaurus-
      - run: pnpm ci --prefer-offline
      - name: Lint 🧶
        run: pnpm run lint
      - name: Build 🏗️
        run: pnpm run build
        # Build is separate deployment on develop branch
        if: ${{ github.ref != 'refs/heads/develop' }}
